### PR TITLE
Fix qt5 build issues

### PR DESCRIPTION
**Pull request by SylvainCorlay**
@goanpeca

### CODE REVIEW

**Comment by goanpeca** [comment]
And maybe the push buttons are also imported from QtWidgets...

**Comment by SylvainCorlay** [comment]
I am still waiting for the build... It is weird that it takes so much time.

**Comment by SylvainCorlay** [comment]
We are almost there.

**Comment by goanpeca** [comment]
@Sylvain, I think that in order to better get used to these changes.. and to change them more easily in the future (spyder included) we should import the needed items on top (like on spyder)

```from PyQt.QtWidgets import QPushButton``` 

etc

**Pull request merged**
