### PR TITLE
PR: Default to application palette

### PR DESCRIPTION
**Pull request by DerekRein**
The default values for the icon color match the application palette. Added a method to reset the icon cache.

### CODE REVIEW

**Comment by ccordoba12** [comment]
@DerekRein, thanks for your contribution. Please rebase on top of master to get the fixes to our tests.

**Comment by dalthviz** [comment]
Fixes #156

**Comment by dalthviz** [comment]
Hi @DerekRein we are thinking on doing a release for QtAwesome `1.1.0` soon and we would like to include this work so we are wondering if it's ok for you if we use it or if you want to help us opening a new PR with it. Let us know!

**Comment by dalthviz** [comment]
Hi again @DerekRein , I did another PR taking your commit via this PR patch. If you don't want for us to include your work in an incoming QtAwesome release please let us know at the [new PR](https://github.com/spyder-ide/qtawesome/pull/176), thanks!

**Pull request closed without merging**
