### PR TITLE
Add travis-ci support, fix readme

### PR DESCRIPTION
**Pull request by goanpeca**

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
Thanks!

**Comment by goanpeca** [comment]
hum... this is not merged...

**Comment by SylvainCorlay** [comment]
Lol!, unlike Carlos, I did not write `merging` :)

**Comment by goanpeca** [comment]
Hehe, I know... I was just messing around :p

**Comment by SylvainCorlay** [comment]
This is great. Thanks a lot for this.

**Pull request merged**
