### PR TITLE
Fix Travis url in README

### PR DESCRIPTION
**Pull request by ccordoba12**
I don't know why you selected camel case for the project name on PyPi, etc, (I really don't like it) but @SylvainCorlay agreed with a lower case name for the repo ;-)

### CODE REVIEW

**Comment by goanpeca** [comment]
@ccordoba12, it is just the name, we think with @SylvainCorlay that it looked better that way. What I do agree on changing is that the install example should be

`pip install qtawesome` as it is more clear, since pip ignores casing AFAIK

**Comment by SylvainCorlay** [comment]
Well this is just a URL change. I am always hesitant between CamelCase and PEP8 when interacting with a library like Qt which uses CamelCase. (For example, when inheriting etc.)

**Comment by ccordoba12** [comment]
I also fixed the image link, but I commited that change directly to master this time. I hope it's ok for such a simple fix :-)

**Comment by SylvainCorlay** [comment]
Thanks! I still don't know why the tests are not getting triggered.

**Pull request merged**
