### PR TITLE
basic change to test travis

### PR DESCRIPTION
**Pull request by SylvainCorlay**
...

### CODE REVIEW

**Comment by goanpeca** [comment]
@ccordoba12 can you give @SylvainCorlay or myself admin rights to the `spyder-ide/qtawesome` repo? 

That way we can try to test what might seem to be the problem with travis-ci not working

**Comment by ccordoba12** [comment]
Done, for both of you. I don't know what happens with Travis, I activate build settings but every time I came back to check, the setting are off...

Well, now it's up to you to fix it :-)

**Comment by goanpeca** [comment]
Thanks :), travis does not like you haha

**Comment by ccordoba12** [comment]
So it seems!! ;-)

**Pull request merged**
