### PR TITLE
PR: Replace qRound (missing in PySide2) with round

### PR DESCRIPTION
**Pull request by gmarull**
PySide2 misses que qRound method. It can be simply replaced by the Python built-in round.

### CODE REVIEW

**Comment by ccordoba12** [comment]
Thanks for your contribution. Quick question: does `round` exist in Python 2 and 3?

**Comment by gmarull** [comment]
Yes, it is available on both Python versions:

https://docs.python.org/2/library/functions.html#round
https://docs.python.org/3/library/functions.html#round

**Comment by imatu5** [comment]
Hello, 

Is it possible to merge his PR as is it pretty useful :+1: 

Thanks,

**Comment by ccordoba12** [comment]
Sure, thanks for remembering us about it.

**Pull request merged**
