### PR TITLE
PR: Add compatibility with PySide2 without impacting PyQt5

### PR DESCRIPTION
**Pull request by stonebig**

### CODE REVIEW

**Comment by ccordoba12** [comment]
Does this supersedes PR #81?

**Comment by stonebig** [comment]
Yes. In the process of making PySide2 more usefull, and so getting more users fighting bugs:
- I converted guidata to 'QtPy' vendored,
- it required this patch.

Now: 
- I have a guidata working, (at 80%)
- but Spyder still doesn't start.

**Comment by stonebig** [comment]
hoping this patch is more acceptable than previous one you rejected

**Comment by ccordoba12** [comment]
Let's use #81, which is simpler.

**Pull request closed without merging**
