### PR TITLE
Update to Font Awesome 5.0.6

### PR DESCRIPTION
**Pull request by homocomputeris**
Hi,

FA has been updated to version 5.
The [main changes](https://fontawesome.com/how-to-use/upgrading-from-4) besides new icons are:
- parting into Regular, Solid and Brands font files
- thus, new prefixes: `far`, `fas`, `fab`, respectively
- changed names of some icons: e.g., the `*-o` ones are now in Regular
- OTF instead of TTF

I've updated the files and added a small example function for names updating focusing on the dictionary used in Spyder for its icons

### CODE REVIEW

**Comment by ccordoba12** [comment]
Thanks a lot for your contribution. However, all our tests are failing, so please fix them.

**Comment by ccordoba12** [comment]
The failures in CircleCI are style issues. Please open its Details link to see what they are about.

**Comment by homocomputeris** [comment]
Style wasn't enforced in the source, so I haven't paid enough attention to it.

**Comment by ccordoba12** [comment]
Sorry, it's enforced by our CIs.

**Comment by homocomputeris** [comment]
Sure, I understand. I just didn't know If I should reformat the code not written by me.

**Comment by SylvainCorlay** [comment]
@homocomputeris you probably want to change your git configuration (email) so that github properly associates it with your account, so that you are properly credited for this work.

**Comment by homocomputeris** [comment]
@SylvainCorlay Thanks for pointing this out. For the moment I'll leave it as it is, if it doesn't affect pull request.

**Comment by homocomputeris** [comment]
A side question: why do CIs build with Qt4? It was discontinued 3 years ago, wouldn't it be easier to drop it?

**Pull request closed without merging**
