### PR TITLE
PR: Add ciocheck and circle ci linux integration

### LINKED ISSUE #53: Add circle ci integration for linux

### PR DESCRIPTION
**Pull request by goanpeca**
Fixes #53 

---

# Description

This add ciocheck as a tool for checking format/autoformating and running tests

More info at [ciocheck](https://github.com/ContinuumIO/ciocheck/)

Also add circle ci integration for running linux tests, will then change travis to make mac tests.

@SylvainCorlay any comments?

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
Is circle ci faster than travis for linux?

**Comment by goanpeca** [comment]
>circle ci faster

Yes, definitely, its the fastest ci

**Comment by SylvainCorlay** [comment]
why not doing osx two on circle ci? To parallelize?

**Comment by goanpeca** [comment]
Cause its better to distribute the load, as conda-forge does... Mac costs on circleci

**Pull request merged**
