### PR TITLE
PR: Rename FontAwesome5 fonts

### LINKED ISSUE #97: minus-circle not working
I'm on Windows 10 with PyQt5.

The following demo:

    from PyQt5 import QtWidgets, QtGui, QtCore
    import qtawesome as qta

    app = QtWidgets.QApplication([])

    icon = qta.icon('fa5s.minus-circle')

    widget = QtWidgets.QWidget()
    layout = QtWidgets.QVBoxLayout()
    button = QtWidgets.QPushButton()
    button.setFixedHeight(100)
    button.setIconSize(QtCore.QSize(100, 100))
    button.setIcon(icon)
    layout.addWidget(button)

    widget.setLayout(layout)

    widget.show()

    app.exec_()

Gives me this:
image

### PR DESCRIPTION
**Pull request by darkvertex**
~(:hand: Please don't merge until the reporters of issue #97 confirm it fixes their issues. :hand:)~
[**Edited 30/09/2018**: Fix confirmed by @flutefreak7 and @jules-ch -- good to go! 👍✔️]

I used [fontname.py](https://github.com/chrissimpkins/fontname.py) to run:
```
python fontname.py "FontAwesome 5 Free Regular" ./qtawesome/qtawesome/fonts/fontawesome5-regular-webfont.ttf
python fontname.py "FontAwesome 5 Free Solid" ./qtawesome/qtawesome/fonts/fontawesome5-solid-webfont.ttf
```
then updated the md5 hashes in `iconic_font.py` so QtAwesome doesn't freak out.

In theory this should fix a bug with QFont merging Regular and Solid for formerly sharing the same font family of "FontAwesome 5 Free".

----

Fixes #97

### CODE REVIEW

**Comment by ccordoba12** [comment]
Looks good, thanks @darkvertex!

**Comment by jules-ch** [comment]
Thanks for taking time to work on this issue @darkvertex 
I couldn't make it work with your changes, don't know if the name has something to do with this.

Tried to change to : 
Font Awesome 5 Free Regular
Font Awesome 5 Free Solid
respectively.

And now it works. Can you try it @flutefreak7.

Commands are : 
`python fontname.py "Font Awesome 5 Free Regular" qtawesome/fonts/fontawesome5-regular-webfont.ttf`
`python fontname.py "Font Awesome 5 Free Solid" qtawesome/fonts/fontawesome5-solid-webfont.ttf`

**Comment by flutefreak7** [comment]
I figured out why the other name didn't work... it was too long!  The max length family name QFont appears to handle for me is 31, which is apparently a well-documented Windows limit.

When I make the Solid name `'a'*31` I get this:
image

When set the Solid font name to  `'a'*32` I get this:
image

[This discussion](https://stackoverflow.com/questions/31901110/what-are-legal-characters-in-font-names) shows that due to limitations on both Mac and Windows, it's wise to stay below 30.

**Comment by darkvertex** [comment]
Ok then, I shortened their names like @flutefreak7 suggested. Good now?

**Comment by jules-ch** [comment]
It's working for me :)

**Comment by darkvertex** [comment]
Great to hear! 😄 That completes the 2 confirmations I wanted.

@ccordoba12: I just squashed my commits and re-pushed, just keeping the last good commit. -- You can merge and release this as `v0.5.1` in my opinion.

**Comment by ccordoba12** [comment]
0.5.1 is out!

**Pull request merged**
