### PR TITLE
Refactor icon and icon_stack into a single codebase. Remove custom painter

### PR DESCRIPTION
**Pull request by goanpeca**

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
As discussed in person, I think that we have agreed on this design. I will checkout the branch real quick and merge this afternoon.

**Comment by goanpeca** [comment]
I did not add the shadow api, I will leave that for the next PR, I left icon_stack and stack, so as not to change the examples...

**Comment by SylvainCorlay** [comment]
I am still unsure whether the shadow API should be there or in Spyder's icon manager. It is a specific use of stack...

**Comment by goanpeca** [comment]
We can make a `shadowed_icon` method to handle this if you prefer

**Comment by ccordoba12** [comment]
*in person*? Are you guys on NYC or France? ;-)

**Comment by SylvainCorlay** [comment]
Actually, technically, it was on gitter...

**Comment by ccordoba12** [comment]
hehehe, I thought you two were meeting in real life ;-)

**Comment by goanpeca** [comment]
When frenchie decides to visit his home town, maybe we can arrange something ;-)

**Comment by SylvainCorlay** [comment]
I am waiting for an invitation to the next PyData Bogota so that we can all meet again.

**Pull request merged**
