### PR TITLE
Fix tests for PyQt5 and add Python 3.5 to the testing matrix

### PR DESCRIPTION
**Pull request by ccordoba12**
This supersedes PR #16.

### CODE REVIEW

**Comment by ccordoba12** [comment]
Hey @goanpeca, why Travis is not working here?

**Comment by ccordoba12** [comment]
Ok, I found the error :-) Tests are now passing for PyQt5 and Python 3.5, so merging!

**Comment by goanpeca** [comment]
Great :+1: what was it ?

**Comment by ccordoba12** [comment]
A syntax error in travis.yml :-p

**Comment by SylvainCorlay** [comment]
:+1:

**Comment by SylvainCorlay** [comment]
@ccordoba12 could you use the PyQt5 conda package without any problem on OS X?

I am getting the following error with Spyder as well as the simplest pyqt applications:

```
This application failed to start because it could not find or load the Qt platform plugin "cocoa".

Reinstalling the application may fix this problem.
Abort trap: 6
```

**Comment by ccordoba12** [comment]
Yes, things with PyQt5 on Mac are working fine for me :-) What's your OS X version? I compiled those packages in 10.9 so they probably don't work on older versions.

**Comment by SylvainCorlay** [comment]
I have 10.10.5.

**Comment by SylvainCorlay** [comment]
I spent a lot of time this morning and yesterday trying to troubleshoot this, with no luck so far.

**Comment by ccordoba12** [comment]
@SylvainCorlay, I can't reproduce your error. I installed our PyQt5 packages in another Mac (10.7 this time) and everything is working fine for me :-)

Two things:

1. Do you have another Qt5 installation in your system? That could be your problem :-)
2. @blink1073, could you install our PyQt5 packages in a conda env to see if they work for you or not? You can do that with

        conda install -c spyder-ide pyqt5

**Comment by SylvainCorlay** [comment]
I don't have another qt5 install. I will try a fresh anaconda install though and get back to you.

**Comment by ccordoba12** [comment]
Then the error could be generated because you have both Qt4 and Qt5 installed in the same environment.

So far I've only tested our packages by creating a new env and installing PyQt5 there (not PyQt4). So that's probably why I'm not seeing the error on my end :-)

I'll test that tomorrow.

**Comment by blink1073** [comment]
I installed a Python 3.5 conda environment with "spyder", ran Spyder, installed PyQt5, and ran Spyder again, without issue.   I am on 10.10.5.

**Comment by SylvainCorlay** [comment]
Works perfectly on a separate install. Sorry for the noise.

**Comment by goanpeca** [comment]
Quelle honte!

**Pull request merged**
